import type {Metadata} from "next";
import "./globals.css";
import HeaderLayout from "@/components/layouts/Header";
import {NextAuthProvider} from "@/components/NextAuthProvider";
import React from "react";


export const metadata: Metadata = {
    title: "NextAuth",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body>
            <NextAuthProvider>
                <HeaderLayout/>
                {children}
            </NextAuthProvider>
        </body>
        </html>
    );
}
